// <auto-generated />
using System;
using BlazorApp2.Server.Helper;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp2.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230109233811_try")]
    partial class @try
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp2.Shared.Buku", b =>
                {
                    b.Property<int>("Id_buku")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_buku"));

                    b.Property<int>("Genre_id")
                        .HasColumnType("int");

                    b.Property<int?>("Genre_id1")
                        .HasColumnType("int");

                    b.Property<string>("Judul_buku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Jumlah_halaman")
                        .HasColumnType("int");

                    b.Property<string>("Penerbit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_buku");

                    b.HasIndex("Genre_id1");

                    b.ToTable("Buku");

                    b.HasData(
                        new
                        {
                            Idbuku = 11,
                            Genreid = 1,
                            Judulbuku = "Dear Nathan",
                            Jumlahhalaman = 250,
                            Penerbit = "Tere"
                        },
                        new
                        {
                            Idbuku = 12,
                            Genreid = 2,
                            Judulbuku = "Dilan 1991",
                            Jumlahhalaman = 250,
                            Penerbit = "Pidi Baiq"
                        },
                        new
                        {
                            Idbuku = 16,
                            Genreid = 3,
                            Judulbuku = "Dibalik 98",
                            Jumlahhalaman = 250,
                            Penerbit = "Ismail"
                        });
                });

            modelBuilder.Entity("BlazorApp2.Shared.Genre", b =>
                {
                    b.Property<int>("Genre_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Genre_id"));

                    b.Property<string>("Nama_Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Genre_id");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Genreid = 1,
                            NamaGenre = "Horor"
                        },
                        new
                        {
                            Genreid = 2,
                            NamaGenre = "Comedi"
                        },
                        new
                        {
                            Genreid = 3,
                            NamaGenre = "Romance"
                        },
                        new
                        {
                            Genreid = 4,
                            NamaGenre = "Fantasi"
                        },
                        new
                        {
                            Genreid = 5,
                            NamaGenre = "Edukasi"
                        });
                });

            modelBuilder.Entity("BlazorApp2.Shared.Buku", b =>
                {
                    b.HasOne("BlazorApp2.Shared.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("Genre_id1");

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
